export const PKG_PREFIX = '@setaria-business-framework'
export const PKG_NAME = 'setaria-business-framework'
export const PKG_CAMELCASE_NAME = 'ElementPlus'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'Element Plus'
